import "dotenv/config";
import { getDb } from "../server/db";
import { sql } from "drizzle-orm";

async function cleanAllTestData() {
  const db = await getDb();
  if (!db) {
    console.error("Database connection failed");
    process.exit(1);
  }

  console.log("Cleaning test data...");

  // 1. Delete all test orders
  await db.execute(sql`DELETE FROM orders WHERE school_id != 1 OR order_number LIKE 'ORD-%' OR school_id = 1`);
  console.log("Cleared orders");

  // 2. Delete test removed cards history
  await db.execute(sql`DELETE FROM removed_cards_history`);
  console.log("Cleared removed_cards_history");

  // 3. Delete approval history
  await db.execute(sql`DELETE FROM approval_history`);
  console.log("Cleared approval_history");

  // 4. Delete id card files & data
  await db.execute(sql`DELETE FROM id_card_files`);
  await db.execute(sql`DELETE FROM id_card_data`);
  await db.execute(sql`DELETE FROM id_cards`);
  console.log("Cleared id_cards, id_card_data, id_card_files");

  // 5. Delete id card requests
  await db.execute(sql`DELETE FROM idCardRequests`);
  console.log("Cleared idCardRequests");

  // 6. Delete template elements and school templates for non-primary templates
  await db.execute(sql`DELETE FROM template_elements WHERE template_id != 1`);
  await db.execute(sql`DELETE FROM school_templates WHERE school_id != 1 OR template_id != 1`);
  await db.execute(sql`DELETE FROM idCardTemplates WHERE id != 1`);
  console.log("Cleared test templates");

  // 7. Delete test users (keep admin, school admin, marketing admin)
  await db.execute(sql`DELETE FROM users WHERE id NOT IN (1, 2, 3) AND (openId LIKE 'test_%' OR email LIKE '%@test.%' OR email LIKE '%@orders.test' OR schoolId != 1)`);
  console.log("Cleared test users");

  // 8. Delete test schools
  await db.execute(sql`DELETE FROM schools WHERE id != 1`);
  console.log("Cleared test schools (kept primary school #1)");

  // 9. Clear audit logs generated by tests
  await db.execute(sql`DELETE FROM audit_logs WHERE school_id != 1 OR school_id IS NULL AND action LIKE '%TEST%'`);
  console.log("Cleared test audit logs");

  // 10. Clear notifications
  await db.execute(sql`DELETE FROM notifications`);
  console.log("Cleared notifications");

  console.log("All test data cleaned successfully!");
  process.exit(0);
}

cleanAllTestData().catch((err) => {
  console.error("Failed to clean test data:", err);
  process.exit(1);
});
